name: Scheduled build
on:
  schedule:
  - cron: '50 9 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger JavaScript webhook on Netlify
      run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
      env:
        TOKEN: ${{ secrets.NETLIFY_JAVASCRIPT_CRON_BUILD_HOOK }}
